export interface Question {
  id: string;
  question: string;
  example: string;
  option1: string;
  option2: string;
}

export const QUESTIONS: Question[] = [
  {
    id: '1',
    question: 'Are you sure?',
    example: 'Soup without meatballs, is that still soup?',
    option1: 'I want meatballs!',
    option2: 'No meatballs please',
  },
  {
    id: '2',
    question: 'Really?',
    example: 'A car without wheels, is that still a car?',
    option1: 'Give me wheels!',
    option2: 'Just roll me away',
  },
  {
    id: '3',
    question: 'Last chance...',
    example: 'Pizza without cheese, is that still pizza?',
    option1: 'Cheese on it!',
    option2: 'Cheeseless is fine',
  },
  {
    id: '4',
    question: 'Unbelievable!',
    example: 'Beer without alcohol, what is that?',
    option1: 'Beer with kick!',
    option2: 'Non-alcoholic is fine',
  },
  {
    id: '5',
    question: 'Seriously?',
    example: 'A beach without water, is that still a beach?',
    option1: 'Water please!',
    option2: 'Dry is fine too',
  },
  {
    id: '6',
    question: 'Okay, last time!',
    example: 'A party without music, is that still a party?',
    option1: 'Turn on the music!',
    option2: 'Silence is golden',
  },
  {
    id: '7',
    question: 'Come on now...',
    example: 'Coffee without caffeine, is that even coffee?',
    option1: 'Caffeine please!',
    option2: 'Decaf works for me',
  },
  {
    id: '8',
    question: 'You can\'t be serious!',
    example: 'A burger without a bun, is that still a burger?',
    option1: 'Bun me up!',
    option2: 'Bunless is fine',
  },
  {
    id: '9',
    question: 'Wait, wait, wait...',
    example: 'Ice cream without ice, is that still ice cream?',
    option1: 'Ice me up!',
    option2: 'Warm cream is fine',
  },
  {
    id: '10',
    question: 'This is crazy!',
    example: 'A sandwich without bread, is that still a sandwich?',
    option1: 'Bread please!',
    option2: 'Breadless works',
  },
  {
    id: '11',
    question: 'No way!',
    example: 'A movie without popcorn, is that even a movie?',
    option1: 'Popcorn now!',
    option2: 'No popcorn needed',
  },
  {
    id: '12',
    question: 'Hold on...',
    example: 'A garden without flowers, is that still a garden?',
    option1: 'Flowers please!',
    option2: 'No flowers needed',
  },
  {
    id: '13',
    question: 'That doesn\'t make sense!',
    example: 'A phone without a screen, is that still a phone?',
    option1: 'Screen me!',
    option2: 'Screenless is fine',
  },
  {
    id: '14',
    question: 'Are you listening?',
    example: 'A cake without frosting, is that still a cake?',
    option1: 'Frost it up!',
    option2: 'No frosting needed',
  },
  {
    id: '15',
    question: 'This is ridiculous!',
    example: 'A bike without pedals, is that still a bike?',
    option1: 'Pedals please!',
    option2: 'Pedalless works',
  },
  {
    id: '16',
    question: 'Think about it...',
    example: 'A book without pages, is that still a book?',
    option1: 'Pages please!',
    option2: 'Pageless is fine',
  },
  {
    id: '17',
    question: 'You\'re kidding, right?',
    example: 'A shower without water, is that still a shower?',
    option1: 'Water me!',
    option2: 'Dry shower works',
  },
  {
    id: '18',
    question: 'Just think...',
    example: 'A door without a handle, is that still a door?',
    option1: 'Handle please!',
    option2: 'Handleless is fine',
  },
  {
    id: '19',
    question: 'Wait a minute...',
    example: 'A pen without ink, is that still a pen?',
    option1: 'Ink me up!',
    option2: 'Inkless works',
  },
  {
    id: '20',
    question: 'That\'s not right!',
    example: 'A bed without sheets, is that still a bed?',
    option1: 'Sheets please!',
    option2: 'Sheetless is fine',
  },
  {
    id: '21',
    question: 'Come on, really?',
    example: 'A lock without a key, is that still a lock?',
    option1: 'Key please!',
    option2: 'Keyless works',
  },
  {
    id: '22',
    question: 'That can\'t be!',
    example: 'A window without glass, is that still a window?',
    option1: 'Glass please!',
    option2: 'Glassless is fine',
  },
  {
    id: '23',
    question: 'Think again...',
    example: 'A watch without hands, is that still a watch?',
    option1: 'Hands please!',
    option2: 'Handless works',
  },
  {
    id: '24',
    question: 'No, that\'s wrong!',
    example: 'A chair without legs, is that still a chair?',
    option1: 'Legs please!',
    option2: 'Legless is fine',
  },
  {
    id: '25',
    question: 'You must be joking!',
    example: 'A ladder without rungs, is that still a ladder?',
    option1: 'Rungs please!',
    option2: 'Rungless works',
  },
  {
    id: '26',
    question: 'That\'s impossible!',
    example: 'A cup without a handle, is that still a cup?',
    option1: 'Handle please!',
    option2: 'Handleless is fine',
  },
  {
    id: '27',
    question: 'Really, truly?',
    example: 'A clock without numbers, is that still a clock?',
    option1: 'Numbers please!',
    option2: 'Numberless works',
  },
  {
    id: '28',
    question: 'I don\'t believe it!',
    example: 'A hat without a brim, is that still a hat?',
    option1: 'Brim please!',
    option2: 'Brimless is fine',
  },
  {
    id: '29',
    question: 'Are you for real?',
    example: 'A shoe without laces, is that still a shoe?',
    option1: 'Laces please!',
    option2: 'Laceless works',
  },
  {
    id: '30',
    question: 'That makes no sense!',
    example: 'A guitar without strings, is that still a guitar?',
    option1: 'Strings please!',
    option2: 'Stringless is fine',
  },
  {
    id: '31',
    question: 'Wait, what?',
    example: 'A umbrella without fabric, is that still an umbrella?',
    option1: 'Fabric please!',
    option2: 'Fabricless works',
  },
  {
    id: '32',
    question: 'You can\'t mean that!',
    example: 'A candle without wax, is that still a candle?',
    option1: 'Wax please!',
    option2: 'Waxless is fine',
  },
  {
    id: '33',
    question: 'That\'s just wrong!',
    example: 'A mirror without glass, is that still a mirror?',
    option1: 'Glass please!',
    option2: 'Glassless works',
  },
  {
    id: '34',
    question: 'I need to ask again...',
    example: 'A pillow without stuffing, is that still a pillow?',
    option1: 'Stuffing please!',
    option2: 'Stuffingless is fine',
  },
  {
    id: '35',
    question: 'This is unbelievable!',
    example: 'A bottle without a cap, is that still a bottle?',
    option1: 'Cap please!',
    option2: 'Capless works',
  },
  {
    id: '36',
    question: 'Say what now?',
    example: 'A lamp without a bulb, is that still a lamp?',
    option1: 'Bulb please!',
    option2: 'Bulbless is fine',
  },
  {
    id: '37',
    question: 'That\'s not possible!',
    example: 'A table without legs, is that still a table?',
    option1: 'Legs please!',
    option2: 'Legless works',
  },
  {
    id: '38',
    question: 'I have to ask...',
    example: 'A wheel without spokes, is that still a wheel?',
    option1: 'Spokes please!',
    option2: 'Spokeless is fine',
  },
  {
    id: '39',
    question: 'You\'re not serious, are you?',
    example: 'A box without sides, is that still a box?',
    option1: 'Sides please!',
    option2: 'Sideless works',
  },
  {
    id: '40',
    question: 'One more time...',
    example: 'A fence without posts, is that still a fence?',
    option1: 'Posts please!',
    option2: 'Postless is fine',
  },
  {
    id: '41',
    question: 'That can\'t be right!',
    example: 'A brush without bristles, is that still a brush?',
    option1: 'Bristles please!',
    option2: 'Bristleless works',
  },
  {
    id: '42',
    question: 'I\'m confused...',
    example: 'A necklace without beads, is that still a necklace?',
    option1: 'Beads please!',
    option2: 'Beadless is fine',
  },
  {
    id: '43',
    question: 'This doesn\'t add up!',
    example: 'A comb without teeth, is that still a comb?',
    option1: 'Teeth please!',
    option2: 'Toothless works',
  },
  {
    id: '44',
    question: 'Are you certain?',
    example: 'A zipper without teeth, is that still a zipper?',
    option1: 'Teeth please!',
    option2: 'Toothless is fine',
  },
  {
    id: '45',
    question: 'That\'s just silly!',
    example: 'A keychain without keys, is that still a keychain?',
    option1: 'Keys please!',
    option2: 'Keyless works',
  },
  {
    id: '46',
    question: 'I must ask again...',
    example: 'A wallet without a wallet, is that still a wallet?',
    option1: 'Wallet please!',
    option2: 'Walletless is fine',
  },
  {
    id: '47',
    question: 'This is getting ridiculous!',
    example: 'A suitcase without a handle, is that still a suitcase?',
    option1: 'Handle please!',
    option2: 'Handleless works',
  },
  {
    id: '48',
    question: 'You sure about that?',
    example: 'A basket without a bottom, is that still a basket?',
    option1: 'Bottom please!',
    option2: 'Bottomless is fine',
  },
  {
    id: '49',
    question: 'That sounds wrong!',
    example: 'A bag without handles, is that still a bag?',
    option1: 'Handles please!',
    option2: 'Handleless works',
  },
  {
    id: '50',
    question: 'Final question...',
    example: 'A pair without two, is that still a pair?',
    option1: 'Two please!',
    option2: 'Oneless is fine',
  },
];

// Function to randomly select up to 5 questions
export const getRandomQuestions = (): Question[] => {
  const shuffled = [...QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 5);
};

