export interface Question {
  id: string;
  question: string;
  example: string;
  option1: string;
  option2: string;
}

export const QUESTIONS: Question[] = [
  {
    id: '1',
    question: 'Are you sure?',
    example: 'Soup without meatballs, is that still soup?',
    option1: 'I want meatballs!',
    option2: 'No meatballs please',
  },
  {
    id: '2',
    question: 'Really?',
    example: 'A car without wheels, is that still a car?',
    option1: 'Give me wheels!',
    option2: 'Just roll me away',
  },
  {
    id: '3',
    question: 'Last chance...',
    example: 'Pizza without cheese, is that still pizza?',
    option1: 'Cheese on it!',
    option2: 'Cheeseless is fine',
  },
  {
    id: '4',
    question: 'Unbelievable!',
    example: 'Beer without alcohol, what is that?',
    option1: 'Beer with kick!',
    option2: 'Non-alcoholic is fine',
  },
  {
    id: '5',
    question: 'Seriously?',
    example: 'A beach without water, is that still a beach?',
    option1: 'Water please!',
    option2: 'Dry is fine too',
  },
  {
    id: '6',
    question: 'Okay, last time!',
    example: 'A party without music, is that still a party?',
    option1: 'Turn on the music!',
    option2: 'Silence is golden',
  },
  {
    id: '7',
    question: 'Come on now...',
    example: 'Coffee without caffeine, is that even coffee?',
    option1: 'Caffeine please!',
    option2: 'Decaf works for me',
  },
  {
    id: '8',
    question: 'You can\'t be serious!',
    example: 'A party without music, is that even a party?',
    option1: 'Music please!',
    option2: 'Silent parties are fine',
  },
  {
    id: '9',
    question: 'Wait, wait, wait...',
    example: 'Pancakes without syrup, is that even breakfast?',
    option1: 'Syrup me up!',
    option2: 'Dry pancakes work',
  },
  {
    id: '10',
    question: 'This is crazy!',
    example: 'A hot dog without a sausage, is that still a hot dog?',
    option1: 'Give me sausage!',
    option2: 'Bread only is fine',
  },
  {
    id: '11',
    question: 'No way!',
    example: 'A movie without sound, is that even a movie?',
    option1: 'Sound please!',
    option2: 'Silent movies work',
  },
  {
    id: '12',
    question: 'Hold on...',
    example: 'A milkshake without milk, is that still a shake?',
    option1: 'Milk it up!',
    option2: 'Milkless shakes work',
  },
  {
    id: '13',
    question: 'That doesn\'t make sense!',
    example: 'A burger without meat, is that still a burger?',
    option1: 'Meat please!',
    option2: 'Veggie burgers work',
  },
  {
    id: '14',
    question: 'Are you listening?',
    example: 'Cereal without milk, is that even breakfast?',
    option1: 'Milk please!',
    option2: 'Dry cereal works',
  },
  {
    id: '15',
    question: 'This is ridiculous!',
    example: 'A sandwich without filling, is that still a sandwich?',
    option1: 'Fill me up!',
    option2: 'Bread only works',
  },
  {
    id: '16',
    question: 'Think about it...',
    example: 'A doughnut without a hole, is that still a doughnut?',
    option1: 'Hole please!',
    option2: 'Holeless works',
  },
  {
    id: '17',
    question: 'You\'re kidding, right?',
    example: 'A margarita without salt, is that even a margarita?',
    option1: 'Salt the rim!',
    option2: 'Saltless works',
  },
  {
    id: '18',
    question: 'Just think...',
    example: 'Pizza without toppings, is that even pizza?',
    option1: 'Top me off!',
    option2: 'Plain pizza works',
  },
  {
    id: '19',
    question: 'Wait a minute...',
    example: 'A cocktail without alcohol, is that even a cocktail?',
    option1: 'Liquor me up!',
    option2: 'Mocktails work',
  },
  {
    id: '20',
    question: 'That\'s not right!',
    example: 'A taco without filling, is that still a taco?',
    option1: 'Fill it up!',
    option2: 'Empty shells work',
  },
  {
    id: '21',
    question: 'Come on, really?',
    example: 'Nachos without cheese, is that even nachos?',
    option1: 'Cheese me up!',
    option2: 'Cheeseless nachos work',
  },
  {
    id: '22',
    question: 'That can\'t be!',
    example: 'Wine without grapes, is that even wine?',
    option1: 'Grape it up!',
    option2: 'Grapeless wine works',
  },
  {
    id: '23',
    question: 'Think again...',
    example: 'A milkshake without ice cream, is that still a shake?',
    option1: 'Ice cream please!',
    option2: 'Creamless shakes work',
  },
  {
    id: '24',
    question: 'No, that\'s wrong!',
    example: 'A cookie without chocolate chips, is that even a cookie?',
    option1: 'Chips please!',
    option2: 'Plain cookies work',
  },
  {
    id: '25',
    question: 'You must be joking!',
    example: 'A burger without pickles, is that even a burger?',
    option1: 'Pickle me!',
    option2: 'Pickleless works',
  },
  {
    id: '26',
    question: 'That\'s impossible!',
    example: 'A smoothie without fruit, is that even a smoothie?',
    option1: 'Fruit it up!',
    option2: 'Fruitless smoothies work',
  },
  {
    id: '27',
    question: 'Really, truly?',
    example: 'A Bloody Mary without vodka, is that even a Bloody Mary?',
    option1: 'Vodka please!',
    option2: 'Virgin Mary works',
  },
  {
    id: '28',
    question: 'I don\'t believe it!',
    example: 'A mojito without mint, is that even a mojito?',
    option1: 'Mint it up!',
    option2: 'Mintless mojitos work',
  },
  {
    id: '29',
    question: 'Are you for real?',
    example: 'A latte without espresso, is that even a latte?',
    option1: 'Espresso please!',
    option2: 'Decaf lattes work',
  },
  {
    id: '30',
    question: 'That makes no sense!',
    example: 'A martini without gin, is that even a martini?',
    option1: 'Gin me up!',
    option2: 'Ginless martinis work',
  },
  {
    id: '31',
    question: 'Wait, what?',
    example: 'A gin and tonic without gin, is that even a G&T?',
    option1: 'Gin me up!',
    option2: 'Tonic only works',
  },
  {
    id: '32',
    question: 'You can\'t mean that!',
    example: 'A smoothie bowl without toppings, is that even a bowl?',
    option1: 'Top me off!',
    option2: 'Plain bowls work',
  },
  {
    id: '33',
    question: 'That\'s just wrong!',
    example: 'A caesar salad without dressing, is that even a caesar?',
    option1: 'Dress me up!',
    option2: 'Dry salads work',
  },
  {
    id: '34',
    question: 'I need to ask again...',
    example: 'A mojito without rum, is that even a mojito?',
    option1: 'Rum please!',
    option2: 'Rumless mojitos work',
  },
  {
    id: '35',
    question: 'This is unbelievable!',
    example: 'A cheeseburger without cheese, is that even a cheeseburger?',
    option1: 'Cheese me!',
    option2: 'Plain burgers work',
  },
  {
    id: '36',
    question: 'Say what now?',
    example: 'A piña colada without rum, is that even a piña colada?',
    option1: 'Rum it up!',
    option2: 'Virgin coladas work',
  },
  {
    id: '37',
    question: 'That\'s not possible!',
    example: 'A sundae without ice cream, is that even a sundae?',
    option1: 'Ice cream please!',
    option2: 'Creamless sundaes work',
  },
  {
    id: '38',
    question: 'I have to ask...',
    example: 'A mimosa without champagne, is that even a mimosa?',
    option1: 'Champagne please!',
    option2: 'OJ only works',
  },
  {
    id: '39',
    question: 'You\'re not serious, are you?',
    example: 'A Bloody Mary without tomato juice, is that even a Bloody Mary?',
    option1: 'Tomato juice please!',
    option2: 'Juiceless works',
  },
  {
    id: '40',
    question: 'One more time...',
    example: 'A chocolate chip cookie without chocolate, is that even a chocolate chip cookie?',
    option1: 'Chocolate please!',
    option2: 'Plain cookies work',
  },
  {
    id: '41',
    question: 'That can\'t be right!',
    example: 'A margarita without tequila, is that even a margarita?',
    option1: 'Tequila please!',
    option2: 'Tequilaless works',
  },
  {
    id: '42',
    question: 'I\'m confused...',
    example: 'A smoothie without a blender, is that even a smoothie?',
    option1: 'Blend me up!',
    option2: 'Unblended works',
  },
  {
    id: '43',
    question: 'This doesn\'t add up!',
    example: 'A whiskey sour without whiskey, is that even a whiskey sour?',
    option1: 'Whiskey please!',
    option2: 'Whiskyless works',
  },
  {
    id: '44',
    question: 'Are you certain?',
    example: 'A cappuccino without foam, is that even a cappuccino?',
    option1: 'Foam it up!',
    option2: 'Foamless works',
  },
  {
    id: '45',
    question: 'That\'s just silly!',
    example: 'A Long Island Iced Tea without alcohol, is that even a Long Island?',
    option1: 'Alcohol please!',
    option2: 'Virgin teas work',
  },
  {
    id: '46',
    question: 'I must ask again...',
    example: 'A daiquiri without rum, is that even a daiquiri?',
    option1: 'Rum it up!',
    option2: 'Rumless works',
  },
  {
    id: '47',
    question: 'This is getting ridiculous!',
    example: 'A bagel without cream cheese, is that even breakfast?',
    option1: 'Cream cheese please!',
    option2: 'Dry bagels work',
  },
  {
    id: '48',
    question: 'You sure about that?',
    example: 'A negroni without gin, is that even a negroni?',
    option1: 'Gin me up!',
    option2: 'Ginless works',
  },
  {
    id: '49',
    question: 'That sounds wrong!',
    example: 'A manhattan without whiskey, is that even a manhattan?',
    option1: 'Whiskey please!',
    option2: 'Whiskyless works',
  },
  {
    id: '50',
    question: 'Final question...',
    example: 'A screwdriver without vodka, is that even a screwdriver?',
    option1: 'Vodka please!',
    option2: 'OJ only works',
  },
];

// Function to randomly select up to 5 questions
export const getRandomQuestions = (): Question[] => {
  const shuffled = [...QUESTIONS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 5);
};

